export default {
  LOCATIONS_SET: 'LOCATIONS_SET',
  PRODUCTS_SET: 'PRODUCTS_SET',
  POSITION_SET: 'POSITION_SET',
  PRICE_SET: 'PRICE_SET',
  RADIUS_SET: 'RADIUS_SET',
  SEARCH_TERM_SET: 'SEARCH_TERM_SET',
  ACTIVE_STORE_SET: 'ACTIVE_STORE_SET'
};
